const BASE_ID = 'BKM_INF';

export const CONTEXT_MENU_CMD_ID = {
  BOOKMARK_ADD_FROM_INPUT_MENU: `${BASE_ID}_BOOKMARK_ADD_FROM_INPUT_MENU`,
  BOOKMARK_ADD_FROM_SELECTION_MENU: `${BASE_ID}_BOOKMARK_ADD_FROM_SELECTION_MENU`,
  TABS_CLOSE_DUPLICATE: `${BASE_ID}_TABS_CLOSE_DUPLICATE`,
  TABS_SORT_BY_TITLE: `${BASE_ID}_TABS_SORT_BY_TITLE`,
  URL_CLEAR: `${BASE_ID}_URL_CLEAR`,
  URL_GET_URL_FROM_URL: `${BASE_ID}_URL_GET_URL_FROM_URL`,
  YOUTUBE_TOGGLE_PAGE_HEADER: `${BASE_ID}_YOUTUBE_TOGGLE_PAGE_HEADER`,
};

export const KEYBOARD_CMD_ID = {
  BOOKMARK_ADD_FROM_INPUT_KBD: `ADD_BOOKMARK_FROM_INPUT_KBD`,
  BOOKMARK_ADD_FROM_SELECTION_KBD: `BOOKMARK_ADD_FROM_SELECTION_KBD`,
};
