const logModuleList = [
  // 'bookmarks.api.js',
  // 'bookmarks.controller',
  // 'browserStartTime',
  // 'cache',
  // 'clearUrlInActiveTab',
  // 'commands.controller',
  // 'contextMenu.controller',
  // 'debounceQueue',
  // 'extensionSettings',
  // 'find-folder.js',
  // 'folder-dated.js',
  // 'get-bookmarks.api.js',
  // 'getUrlFromUrl',
  // 'history.api',
  // 'incoming-message',
  // 'init-extension',
  // 'memo',
  // 'moveFoldersByName.js',
  // 'page.api.js',
  // 'runtime.controller',
  // 'storage.api.js',
  // 'storage.controller',
  // 'tabs.api.js',
  // 'tabs.controller',
  // 'tagList-getRecent.js',
  // 'tagList-highlight.js',
  // 'tagList.js',
  // 'url-search.api',
  // 'url.api.js',
  // 'windows.controller',
]
export const logModuleMap = Object.fromEntries(
  logModuleList.map((moduleKey) => [moduleKey, true])
)
