
export const USER_SETTINGS_OPTIONS = {
  CLEAR_URL_FROM_QUERY_PARAMS: 'CLEAR_URL_FROM_QUERY_PARAMS',
  SHOW_PATH_LAYERS: 'SHOW_PATH_LAYERS',
  SHOW_PREVIOUS_VISIT: 'SHOW_PREVIOUS_VISIT',
  SHOW_BOOKMARK_TITLE: 'SHOW_BOOKMARK_TITLE',
  SHOW_PROFILE: 'SHOW_PROFILE',
  ADD_BOOKMARK: 'ADD_BOOKMARK',
  // MARK_VISITED_URL: 'MARK_VISITED_URL',
}

export const SHOW_PREVIOUS_VISIT_OPTION = {
  NEVER: 0,
  ONLY_NO_BKM: 1,
  ALWAYS: 2,
}

const o = USER_SETTINGS_OPTIONS

export const USER_SETTINGS_DEFAULT_VALUE = {
  [o.CLEAR_URL_FROM_QUERY_PARAMS]: true,
  [o.SHOW_PATH_LAYERS]: 1, // [1, 2, 3]
  [o.SHOW_PREVIOUS_VISIT]: SHOW_PREVIOUS_VISIT_OPTION.ALWAYS,
  [o.SHOW_BOOKMARK_TITLE]: false,
  [o.SHOW_PROFILE]: false,
  [o.ADD_BOOKMARK]: false,
}

export const TAG_LIST_VISIBLE_LIMIT = 25;